language: node_js
node_js: node

# main script: install, build, test
script:
  - echo "Installing deps"
  - yarn install
  - echo "Building GUI"
  - yarn run elm
  - echo "Running test"
  - yarn run test
