# name of your github action
name: Auto-release
# this will help you specify where to run 
on:
  push:
    branches:
    # this will run on the electron branch
      - master
# this is where the magic happens, each job happens in parallel btw
jobs:
  build:
    strategy:
      matrix:
        os: [ macOS-latest, ubuntu-latest ]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@master
      with:
        ref: master
    - uses: actions/setup-node@master
      with:
        node-version: 10.16
    - name: Sanity check
      run: ls
    - name: Install deps
      run: yarn install
    - name: Build release
      run: yarn run release
    - name: Check dist
      run: ls dist
