name: release
on:
  push:
    branches:
    # this will run on the master branch
      - master
jobs:
  build:
    # run on mac and linux
    strategy:
      matrix:
        os: [ macOS-latest, ubuntu-latest ]
    runs-on: ${{ matrix.os }}
    steps:
    # checkout master
    - uses: actions/checkout@master
      with:
        ref: master
    # setup node
    - uses: actions/setup-node@master
      with:
        node-version: 10.16
    # See if we're on the right repo lol
    - name: Sanity check
      run: ls
    - name: Install deps
      run: yarn install
    - name: Build release
      run: yarn release --publish never
    - name: Check dist
      run: ls dist
